[WIP]User gets notification when new comments are added
CraftAcademy/food_hub pull request #24
Opened 2018-06-12 12:01 UTC by GeorgeJLewis

https://www.pivotaltracker.com/story/show/158257202
* adds feature file with user story

2018-06-12 13:37 UTC, magnus-thor requested changes

2018-06-12 13:37 UTC, magnus-thor commented on features/step_definitions/basic_steps.rb
> +
remove empty line

2018-06-12 13:37 UTC, magnus-thor commented on spec/models/recipe_spec.rb
> +  # end
uncomment or delete commented out lines

2018-06-12 13:37 UTC, magnus-thor commented on features/user_gets_notification_when_new_comments_are_added.feature
> +    Scenario: A user can see when someone comments on a recipe
fix the indentation

2018-06-12 13:37 UTC, magnus-thor commented on app/models/recipe.rb
> +  # end
uncomment or delete commented out lines

2018-06-12 13:49 UTC, magnus-thor submitted a review, later dismissed

2018-06-13 08:47 UTC, faraznaeem approved these changes

2018-06-13 08:47 UTC, merged